devices_tab = 'com.amazon.dee.app:id/tab_channels_device'
add_devices_plus = 'image-test'
add_thermostat = '//android.view.ViewGroup[@content-desc="Thermostats"]/android.view.ViewGroup[1]'
add_device_option = 'addMenuItem_addDevice-primary'
brand_amazon = '(//android.widget.Button[@content-desc="Amazon"])[2]'

# Buttons
no_button = '//android.widget.Button[@content-desc="No"]'
yes_button = '//android.widget.Button[@content-desc="Yes"]'
next_button = '//android.widget.Button[@content-desc="Next"]'
allow_button = '//android.widget.Button[@content-desc="Allow"]'
skip_button = '//android.widget.Button[@content-desc="Skip"]'
later_button = '//android.widget.Button[@content-desc="Later"]'
done_button = '//android.widget.Button[@content-desc="Done"]'
no_barcode = '//android.widget.Button[@content-desc="Don\'t Have A Barcode?"]'
no_high_voltage_button = '//android.widget.Button[@content-desc="No High Voltage"]'
setup_thermostats_button = '//android.widget.Button[@content-desc="Set Up Thermostats"]'
yes_heat_is_on = '//android.widget.Button[@content-desc="Yes, Heat Is On"]'
yes_fan_is_on = '//android.widget.Button[@content-desc="Yes, Fan Is On"]'

honeywell_thermostat = 'mosaic.BaseLink'
wifi_the_boys = '(//android.widget.RadioButton[@content-desc="The BOYS"])[1]'
natural_Gas_furnace = '(//android.widget.RadioButton[@content-desc="Natural Gas"])[2]'
electric_furnace = '(//android.widget.RadioButton[@content-desc="Electric"])[2]'
oil_furnace = '(//android.widget.RadioButton[@content-desc="Oil"])[2]'
hunches_oobe = '(//android.widget.RadioButton[@content-desc="Alexa automatic control"])[1]'
schedule_oobe = '(//android.widget.RadioButton[@content-desc="Daily schedule"])[1]'
off_mode = 'ThermostatControl::mode=OFF'
popup_Later = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.Button[1]/android.widget.TextView'

# HVAC Configs
S = '0 S1'
ALA = '1 A-L/A'
S_2 = '2 S2'
OB = '3 O/B'
Y = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[3]/android.view.ViewGroup[1]/android.widget.CheckBox' #'4 Y'
W2Aux = '5 W2/Aux'
Y2 = '6 Y2'
E = '6 Y2'
G = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[5]/android.view.ViewGroup[1]/android.widget.CheckBox' #'8 G'
W = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[5]/android.view.ViewGroup[2]/android.widget.CheckBox' #'9 W'
C = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[6]/android.view.ViewGroup[1]/android.widget.CheckBox'  #'10 C'
K = '11 K'
U = '12 U1'
R = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout[3]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[7]/android.view.ViewGroup[2]/android.widget.CheckBox'    #'13 R'

# Different Way
add_new_device_plus = '//android.widget.Button[@content-desc="Add a new device or group"]'
add_device = '(//android.widget.Button[@content-desc="Add Device Echo, Smart Home, and Accessories"])[1]'
